### ISSUE TITLE
TypeError: _a.replaceAll is not a function

### ISSUE THREAD

**Issue by s-steephan** [PrinterFramework/CLI#1]
I am getting the following error when I try to create a new project.

```sh
 $ printer new printerproject
👷  Could not load Printer config
👷  Generating new Printer project
    ✅  Created .babelrc
    ✅  Created .gitignore
    ✅  Created .gitkeep
    ✅  Created public/.gitkeep
    ✅  Created pages/_app.tsx
    ✅  Created pages/_document.tsx
    ✅  Created pages/index.tsx
(node:53216) UnhandledPromiseRejectionWarning: TypeError: _a.replaceAll is not a function
    at C:\Users\Steephan Selvaraj\AppData\Roaming\npm\node_modules\@printerframework\cli\dist\src\generators\new.js:105:208
    at step (C:\Users\Steephan Selvaraj\AppData\Roaming\npm\node_modules\@printerframework\cli\dist\src\generators\new.js:33:23)
    at Object.next (C:\Users\Steephan Selvaraj\AppData\Roaming\npm\node_modules\@printerframework\cli\dist\src\generators\new.js:14:53)
    at C:\Users\Steephan Selvaraj\AppData\Roaming\npm\node_modules\@printerframework\cli\dist\src\generators\new.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\Steephan Selvaraj\AppData\Roaming\npm\node_modules\@printerframework\cli\dist\src\generators\new.js:4:12)
    at generateNewProject (C:\Users\Steephan Selvaraj\AppData\Roaming\npm\node_modules\@printerframework\cli\dist\src\generators\new.js:51:12)
    at C:\Users\Steephan Selvaraj\AppData\Roaming\npm\node_modules\@printerframework\cli\dist\src\printer.js:69:67
    at step (C:\Users\Steephan Selvaraj\AppData\Roaming\npm\node_modules\@printerframework\cli\dist\src\printer.js:35:23)
    at Object.next (C:\Users\Steephan Selvaraj\AppData\Roaming\npm\node_modules\@printerframework\cli\dist\src\printer.js:16:53)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:53216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:53216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by s-steephan** [comment]
My current environment versions are below.
```sh
printer - 1.2.0
nodejs - 14.18.2
npm - 6.14.15
```

**Comment by ChrisCates** [comment]
Hey @s-steephan! Thanks for checking it out.
I'm going to work on debugging it for Windows now.

If you have access to Mac OS or Linux. You should be able to use it.

**Comment by ChrisCates** [comment]
I've just tested this on Windows 11. Could not reproduce the issue.
I tried nvm node v14 and still no luck attempting to reproduce the issue.
